### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NdaruAjaa** [xrde4/XNoNickSpace#1]
How do I set it so that spaced names cannot join the server?

**Comment by xrde4** [comment]
Hello,

To ensure that users with spaced names cannot join the server, you should set the "Expert" status in the plugin's configuration. 
If you have any more questions or need further assistance, please feel free to ask. We're here to help!

Best regards.

**Comment by NdaruAjaa** [comment]
OK, thank you very much, I have succeeded
